"""added models

Revision ID: 11786e063e6
Revises: 4c2ef6417ec
Create Date: 2015-10-19 09:06:55.875043

"""

# revision identifiers, used by Alembic.
revision = '11786e063e6'
down_revision = '4c2ef6417ec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('agenda', sa.Text(), nullable=True),
    sa.Column('social', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.drop_table('events')
    ### end Alembic commands ###
